version: "1"
services:
  - type: web
    name: get-a-rid
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEBUG
        value: ""
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
